### ISSUE TITLE
Comparison to mori?

### ISSUE THREAD

**Issue by atroche** [disya2/fun-lib#1]
Would be interesting to see how / why it's different to http://swannodette.github.io/mori/ in usage / implementation

**Comment by disya2** [comment]
It should be (one day) very similar in usage but it fundamentally differs in implementation. While mori is basically a ClojureScript wrapped as a library for JavaScript, fun-lib utilizes ES6 features to provide handy sequence library along with data types. It also treats any sequence as a JavaScript iterator, i.e. something that has Symbol.iterator, which makes it interoperable with future JavaScript code and legacy arrays/strings.
